# server port
server:
  port: 8081
  
# data base
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_springboot
    password: 1234

# mybatis
mybatis:
  mapper-locations: mapper/*.xml 